
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'platform_core'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'aero_grid_platform'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  platform_core:                                                                                    # Importante specificare il percorso della directory.
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: view
      +schema: int
    marts:
      +materialized: table
      +schema: mart

seeds:                                                                                              # Configurazione dei seeds (lookup table)
  platform_core:
      turbine_codes:                                                                                # Nome del file seed
        +alias: stg_lookup_turbine_error_code                                                       # Nome della tabella
        +schema: stg                                                                                # Andiamo a distribuire i seed nel layer stg
        +column_types:
          code: string
          severity: string
          description: string

snapshots:
  platform_core:                                                                                    # Il nome del progetto dbt
    +target_schema: aero_grid_snapshots                                                             # Lo schema finale 


vars:
  telemetry_start_date: 7                                                                           # Variabile che imposta di considerare solo le ultime 7 rilevazioni
